### ISSUE TITLE
Project solution

### ISSUE THREAD

**Issue by Bloodmanovski** [Zeex/sampgdk#120]
Hi, could you make for this a project solution for Visual Studio? I think it could be better when everyone could download a simple predefined solution like new.pwn in pawno and start developing without setting a whole project with cmake and other win-unlike tools.

**Comment by vinigas** [comment]
There is tutorial how to make Visual Studio solution.
https://github.com/Zeex/sampgdk/wiki/Setting-up-GDK-with-CMake

I have made it. But it will build only dll. I have a question how to make solution (or what i need to do) to build linux versions ?

**Comment by Zeex** [comment]
@vinigas Smply follow the same steps on a Linux machine. On Linux CMake will generate a Makefile instead of a solution, so you would just type `make` in your terminal to build the project. ad get a `.so` file.

**Comment by Zeex** [comment]
Starting from next release the binary distribution will include a `blank.cpp` that is similar to `new.pwn` in Pawno, i.e. it will contain all callbacks with their default values, and some other boilerplate code.
