### ISSUE TITLE
callbacks not called if sa-mp decides to call them only for first filterscript (filterscripts[0])

### ISSUE THREAD

**Issue by grasmanek94** [Zeex/sampgdk#124]
I was implementing OnClientCheckResponse into my gamemode into sampgdk and after everything works (sending, receiving, etc, have done analysis with wireshark) and even the pawn filterscript script callback get executed. OnClientCkeckResponse is executed, it does not execute in the sampgdk mode.

@definition file add:

    OnClientCheckResponse

@sampgdk.c add

	SAMPGDK_NATIVE(int, SendClientCheck(int playerid, char type, int memAddr, short memOffset, short byteCount))
	{
		static AMX_NATIVE native;
		cell retval;
		cell params[6];
		sampgdk_log_debug("SendClientCheck(%d, %d, %d, %d, %d)", playerid, type, memAddr, memOffset, byteCount);
		if (unlikely(native == NULL)) {
			native = sampgdk_native_find_warn_stub("SendClientCheck");
		}
		params[0] = 5 * sizeof(cell);
		params[1] = (cell)playerid;
		params[2] = (cell)type;
		params[3] = (cell)memAddr;
		params[4] = (cell)memOffset;
		params[5] = (cell)byteCount;
		retval = native(sampgdk_fakeamx_amx(), params);
		return (int)(retval);
	}

	typedef bool (SAMPGDK_CALLBACK_CALL *OnClientCheckResponse_callback)(int playerid, int type, int arg, int response);
	static bool _OnClientCheckResponse(AMX *amx, void *callback, cell *retval) {
		bool retval_;
		int playerid;
		int type;
		int arg;
		int response;
		sampgdk_param_get_cell(amx, 0, (void *)&playerid);
		sampgdk_param_get_cell(amx, 1, (void *)&type);
		sampgdk_param_get_cell(amx, 2, (void *)&arg);
		sampgdk_param_get_cell(amx, 3, (void *)&response);
		sampgdk_log_debug("OnClientCheckResponse(%d, %d, %d, %d)", playerid, type, arg, response);
		retval_ = ((OnClientCheckResponse_callback)callback)(playerid, type, arg, response);
		if (retval != NULL) {
			*retval = (cell)retval_;
		}
		return (retval_ != false);
	}

@sampgdk.c register callbacks add:

	if ((error = sampgdk_callback_register("OnClientCheckResponse", _OnClientCheckResponse)) < 0) {
		return error;
	}

pawn filterscript:

	#include <a_samp>

	main(){}

	public OnRconCommand(cmd[])
	{
		return 0;
	}

	forward OnClientCheckResponse(playerid, type, arg, response);
	public OnClientCheckResponse(playerid, type, arg, response)
	{
		return 1;
	}

execute:

	SendClientCheck(playerid, 0x47, 1598, 0, 0x10);

**Comment by Zeex** [comment]
No, currently not. But something like CallRemoteFunction("OnClientCheckResponse, ...) from a FS might do the trick. Also, it's called for all filterscripts, not just the first one (you have to return 0).

**Comment by TheRoW** [comment]
Zeex you can post your filterscript test ? I want to see how you maked function to work.

**Comment by Catalin-Mihai** [comment]
Can you provide us an example for this?
