### ISSUE TITLE
Help with OnPlayerCommandText

### ISSUE THREAD

**Issue by uMarcelo** [Zeex/sampgdk#130]
I'm use this code:
	if (cmd.substr(0, 3) == "/pm")
	{
		std::string param = cmd.substr(3);
		int id;
		char text[256];
		int argCount = sscanf(param.c_str(), "%d %s", &id, text);
		if (argCount < 2) return SendClientMessage(playerid, 0x00FF00FF, "error");
		SendClientMessage(id, 0x00FF00FF, text);
		return true;
	}

But I have a problem, I can use this command, and so: /pm playerid text; and so: /pmplayeridtext
How i can fix this problem? I wan't to fix the second variant 2 (/pmplayeridtext) and use only variant 1 (/pm playerid text)..

thanks in advance, pardon to gramma, i'm from Russia and use google translate.

**Comment by Zeex** [comment]
Sorry, this isn't an appropriate place for C/C++ questions. You'd better off asking this on some C/C++ forums or a Q&A site like [StackOverflow](http://stackoverflow.com).
