### ISSUE TITLE
Some Missing Functions

### ISSUE THREAD

**Issue by IntelliSun** [Zeex/sampgdk#131]
It appears that some functions are missing from the sdk headers, I don't know if they are missing from the source though. Some of functions are new but some are very old, some of the missing functions are:
* GetGravity

Is there a reason for them being left out or am I just missing them? 
Thanks!

**Comment by Zeex** [comment]
Aren't they defined in a_samp.h?

**Comment by IntelliSun** [comment]
Not as far as I know, I also looked for them in the documentation, could not find them.

**Comment by IntelliSun** [comment]
Well I run this small script I threw up:
```C#
var counter = 0;

var directory = Console.ReadLine();
var files = Directory.GetFiles(directory, "*", SearchOption.AllDirectories);
foreach (var file in files)
{
        var fileContent = File.ReadAllText(file);
        counter += fileContent.Contains("GetGravity") ? 1 : 0;
}

Console.WriteLine("Looked in {0} files; {1} matches.", files.Length, counter);
```

It could not find anything.

**Comment by grasmanek94** [comment]
The reason they are being left out is easy:

http://wiki.sa-mp.com/wiki/GetGravity

Important
Note
	This function is not defined by default. Add 'native GetGravity();' under the inclusion of a_samp.inc to use it.

**Comment by IntelliSun** [comment]
@grasmanek94 It's probably the case, though it needs to be fixed I'd assume. About the functions other than `GetGravity` I did find them as you suggested, maybe I miss-typed something the first time because I run the tests only for `GetGravity`.

**Comment by Zeex** [comment]
I'll add GetGravity(), thanks.
