### ISSUE TITLE
Executing public functions(Gamemode) with SAMPGDK

### ISSUE THREAD

**Issue by crodriguespt** [Zeex/sampgdk#134]
Hey there!
I noticed that We can't call Public functions(in the gamemode) using sampgdk.
Is there any possibility to add the support for Public Functions handling in the future releases of sampgdk(with the same syntax as the Native functions)?

Thanks

**Comment by Zeex** [comment]
I could add something like this but it's seems to be something rather out of scope of this library (and slightly backwards to the current functionality). I personally would love to use something like [this](https://gist.github.com/Zeex/5217723) instead, rewritten using latest C++11/14 features like variadic templates, etc, i.e.  someting more type-safe and modern and less error-prone.
