### ISSUE TITLE
IDL doesn't support default parameters

### ISSUE THREAD

**Issue by grasmanek94** [Zeex/sampgdk#135]
It seems the algorithm used to generate all the needed files for sampgdk doesn't support default values. Could you please update this?

    [native, noimpl] int SetTimer([in] int interval, [in] bool repeat, [in] TimerCallback callback, [in, out] void param, [in, out] void owner = NULL); //errors

**Comment by Zeex** [comment]
It does support default parameters but it doesn't know what NULL means, it thinks that's a named constant.

**Comment by grasmanek94** [comment]
Ah okay :)
