### ISSUE TITLE
OnRconCommand not getting called

### ISSUE THREAD

**Issue by 123marvin123** [Zeex/sampgdk#139]
Hi,

so far, every callback I tested works, except OnRconCommand. I know that you need at least 1 filter script for it to trigger, but I think your FakeAMX takes care of it. But even with 1 filter script in my server.cfg it won't trigger.

Here is my code:
```c++
PLUGIN_EXPORT inline bool PLUGIN_CALL OnRconCommand(const char* cmd)
{
	printf("RCON: %s", cmd);
	return true;
}
```

And of course, I added OnRconCommand to my .def file.

**Comment by ikkentim** [comment]
Do your return 0 in your filterscript?

**Comment by 123marvin123** [comment]
No, I don't. My filter script does not even include a OnRconCommand callback.
I even tried with 0 filter scripts, but not working either.

**Comment by ikkentim** [comment]
You need to. Use that filterscript I just posted and it will work just fine.

**Comment by 123marvin123** [comment]
Thanks, it's working now.
