### ISSUE TITLE
Implementation the gamemode C++ in samp server

### ISSUE THREAD

**Issue by Ymil** [Zeex/sampgdk#144]
Hello, your reposite is excellent, thanks. I'm question the implementation the gamemode in samp server, whats its procedural?
Where save files after compilation ?
hope for your response.
Bye.

**Comment by Zeex** [comment]
If you're doing everything right after the compilation is finished you should see a .dll or .so binary file (depend on your OS) in your output directory. You'll need to load this file the same way as you would load other plugins, i.e. add `your-plugin-name` to the `plugins` line of server.cfg.

**Comment by Zeex** [comment]
I think I didn't exactly understand your question but it seems that you're having difficulties with creating plugins in general. If that is the case I would suggest reading this plugin development guide on SA-MP forums, it explains everything in detail: http://forum.sa-mp.com/showthread.php?t=295798

**Comment by Mohsen7s** [comment]
It's much more than excellent,

**Comment by Ymil** [comment]
And the plugin is the gamemode, is true ?

**Comment by Zeex** [comment]
Yes.
