### ISSUE TITLE
public hook control

### ISSUE THREAD

**Issue by JernejL** [Zeex/sampgdk#146]
There is no documentation on this, but are hooked publics first called in my plugin or the gamemode script? 
I'd actually like to have a way to control this - it is a bit important for my new plugin to be called after the scripts as it will be providing utility callbacks, which might interfere depending on how the script is written. 
 
And yes, i finally got my visual studio set up and created a working compiling environment, so i'm going ahead full speed to upgrade math plugin into something more useable :)

**Comment by ikkentim** [comment]
At the moment it's called in the order filterscripts > gdk > gamemodes

**Comment by JernejL** [comment]
And there is no way to alter that?

**Comment by ikkentim** [comment]
No, not without changing up the gdk code

 I can't speak for Zeex, but seeing this is GDK aims on helping developing gamemodes in c++, I don't think he'll make this happen.

There are lots of complications when you try to change this. As far as I can see, in the current way the hooks work, every plugin which uses gdk needs call the next callback in the chain before it calls its own implementation (which is the opposite of what currently happens) to achieve what want. 

The gdk handling the call before the gamemode is very logical. This way a plugin can then decide whether to call the gamemode's implementation of the callback.

I have no idea of what you try to achieve, but couldn't you simply create a native which executes your logic and call this from the script (possible using als hooks)?

**Comment by JernejL** [comment]
My purpose is to provide some extra callbacks on some events.. like tracking when player weapondata has changed, and provide that event with a public call. I imagine it could be a conflict if this was called before onplayerupdate in amx, but maybe it won't be much of a issue.
