### ISSUE TITLE
gettime() replacement

### ISSUE THREAD

**Issue by Vinigas** [Zeex/sampgdk#147]
How to replace PAWN gettime() to C++ ?

I want to get timestamp integer

**Comment by Zeex** [comment]
There's plenty of answers on google, this one seems to be the most portable as it's part of C++11:

http://stackoverflow.com/a/19555298

Basically it boils down to this:

```c++
#include <chrono>

...
auto timestamp = std::chrono::system_clock::now().time_since_epoch().count();
std::cout << "the timestamp is: " << timestamp << std::endl;
```

See also: http://en.cppreference.com/w/cpp/chrono/time_point/time_since_epoch
