### ISSUE TITLE
GetPlayerPoolSize()

### ISSUE THREAD

**Issue by CFourFuntik** [Zeex/sampgdk#148]
Check the GetPlayerPoolSize function. It doesnt work correctly. It always returns 0.

**Comment by ikkentim** [comment]
How many players were connected when you tested this? It returns the highest ID, so if only 1 player was connected it would indeed return 0 still.

**Comment by CFourFuntik** [comment]
Oh, sorry. I think that GetPlayerPoolSize() returns count

**Comment by ikkentim** [comment]
`Gets the highest playerid currently in use on the server` http://wiki.sa-mp.com/wiki/GetPlayerPoolSize
