### ISSUE TITLE
SetTimer won't call the callback (amalgamation)

### ISSUE THREAD

**Issue by drakeee** [Zeex/sampgdk#149]
For some reason SetTimer does not want to work. I'm using the latest amalgamation and the following code:
```
PLUGIN_EXPORT unsigned int PLUGIN_CALL Supports()
{
	return sampgdk::Supports() | SUPPORTS_PROCESS_TICK;
}

void SAMPGDK_CALL PrintTickCountTimer2(int timerid, void *params) {
	sampgdk::logprintf("Tick count: %d", GetTickCount());
}

PLUGIN_EXPORT bool PLUGIN_CALL OnGameModeInit()
{
	sampgdk::logprintf("GameModeInit");
	SetTimer(1000, true, PrintTickCountTimer2, 0);
	return true;
}

PLUGIN_EXPORT void PLUGIN_CALL ProcessTick()
{
	sampgdk::ProcessTick();
}
```

OnGameModeInit and ProcessTick are called, but the function defined in SetTimer won't.
Is there something that i miss or did wrong or it's just don't work for some reason.

**Comment by Zeex** [comment]
Are you sure that `ProcessTick` is getting called at all? You might have forgotten to export it if you're using Windows. If not, try turning on debug logging, i.e.set the `SAMPGDK_LOG` environment variable to `+id`.

**Comment by drakeee** [comment]
Yeah i'm sure, i put logprint in ProcessTick to see is it called correctly and it flood the server. Well I set SAMPGDK_LOG to +id as you mentioned but it do not give any log for me and for some reason if I build the plugin in Debug mode the SetTimer works perfectly otherwise (in Release mode) it wont call.

**Comment by drakeee** [comment]
Well found an interesting thing: if I set "Whole Program Optimization" to "No Whole Program Optimization" the timer works perfectly in any build mode otherwise it won't call.

**Comment by Zeex** [comment]
Did you define `SAMPGDK_AMALGAMATION` like the how-to-use-amalgamation.txt file says?

**Comment by drakeee** [comment]
After I defined it on top of the main file (put the define in the first line) still not working.

**Comment by Zeex** [comment]
Go to Project Properties -> C/C++ Preprocessor -> Additional preprocessor definitions and add `SAMPGDK_AMALGAMATION` there, then recompile. This should fix it.

**Comment by drakeee** [comment]
It works perfectly now but you should add this little info in the readme (with some examples (if possible of course)).
