### ISSUE TITLE
Set || Get VehicleParamsEx bool<-->int*

### ISSUE THREAD

**Issue by Vinigas** [Zeex/sampgdk#151]
Why SetVehicleParamsEx parameters is bool, while GetVehicleParamsEx parameters is integer* ? Shouldn't it be bool* logically ? It's not problem, just saying. :)

**Comment by kurta999** [comment]
No, that should be integer. In samp these parameters can have three values: -1, 0, 1

**Comment by Vinigas** [comment]
So value -1 means not_exist/error ?

**Comment by Vinigas** [comment]
yay, found out: "If a parameter is unset (SetVehicleParamsEx not used beforehand) the value will be -1 ('unset').". Sorry :)
