### ISSUE TITLE
SampGDK version

### ISSUE THREAD

**Issue by JernejL** [Zeex/sampgdk#152]
Related to this: https://github.com/samp-incognito/samp-streamer-plugin/issues/78
 
I have no real way to find out which plugin (or sa-mp version) is cause of the issue.
Could as a convinience every sampgdk plugin in future output sampgdk version during plugin load? it would make it much easier to identify out of date plugins and upgrade them.

**Comment by Zeex** [comment]
I agree, this may be useful for debugging. I'll make the library log this at the info level (can be enabled with `SAMPGDK_LOG=+i`) to not clutter the plugin's actual output.
