### ISSUE TITLE
OnPlayerGiveDamageActor - no publics called in main amx script

### ISSUE THREAD

**Issue by JernejL** [Zeex/sampgdk#153]
I am not totally sure as to what is going on so i'm submitting a bug incase you might know what causes this. 
 
I use OnPlayerGiveDamageActor public in my amx script, it works great, but only on windows build. 
 
The script is identical on linux yet it doesn't function there. I suspect it could be some issue inside sampgdk that i use (in streamer and mathplugin). 
 
I have locally updated mathplugin to latest sampgdk 4.3, i have also recompiled streamer plugin on linux with same sampgdk, all works fine except on linux server - there the OnPlayerGiveDamageActor is not called at all. 
 
My plugins are:
 
MapAndreas.so TranslationPlugin.so socket.so mysql_static.so gvar.so KeyVal.so rwthread.so PlayerDataRecorder.so crashdetect.so streamer.so SampUtils.so QIterator.so  nativechecker.so
 
To my knowledge only samputils (math plugin) and streamer use sampgdk. 
 
So i'm wondering if this could be caused by sampgdk, i can run various tests as needed.

**Comment by Zeex** [comment]
Indeed this might be a bug in sampgdk, I'll look into it on my Linux system.

Meanwhile, can you see if OnPlayerGiveDamageActor is broken in other scripts or it's just your particular gamemode?

**Comment by JernejL** [comment]
OnPlayerGiveDamageActor is one of last publics added in 0.3.7 - that might be related. 

I will test OnPlayerGiveDamageActor with and without plugins in a blank gamemode.

**Comment by Zeex** [comment]
BTW you can also enable debug logging in sampgdk by setting `SAMPGDK_LOG` variable:

`SAMPGDK_LOG=+id ./samp03svr'

and check what happens when `OnPlayerGiveDamageActor` gets called. If there is not such callback in the output it must be a bug

**Comment by JernejL** [comment]
It turned out this was a sa-mp issue in the end. 
 
Apparently SetActorInvulnerable is needed for callback to be called on linux version (as it says in wiki documentation) but is called regardless on windows version.. it behaves different on linux basically and i suspected sampgdk by mistake. 
 
On the good side, i have upgraded math plugin to latest sampgdk. 
 
I will close the bug report and report this to kalcor.
