### ISSUE TITLE
OnPublicCall not cancelable

### ISSUE THREAD

**Issue by 123marvin123** [Zeex/sampgdk#156]
Is there any possibility to cancel further execution (like returning 0 in pawn) when using OnPublicCall? When I set the return value to 0 and return false, the OnPlayerRequestSpawn (just an example) event will still be called in the pawn game mode, overriding my values.

**Comment by ikkentim** [comment]
Yes, just return false

http://zeex.github.io/sampgdk/doc/html/group__interop.html#ga9957c2761fb2016db71c9d8a3b42cb75

**Comment by 123marvin123** [comment]
But it does not work, it still executes the pawn callback.

**Comment by ikkentim** [comment]
Testing...

**Comment by 123marvin123** [comment]
Little example:
´´´
if (shouldCancelCallback(name, result)) {
	sampgdk_logprintf("Canceling callback %s with returnvalue %i", name, *retval);
	return false;
}
´´´

outputs: Canceling callback OnPlayerRequestSpawn with return value 0
but I still spawn

**Comment by WopsS** [comment]
Can you show us exactly how you do that? In your example you call the callback that you should cancel before that.

**Comment by 123marvin123** [comment]
This is my full function:
```cpp
PLUGIN_EXPORT bool PLUGIN_CALL OnPublicCall(AMX *amx, const char *name, cell* params, cell *retval)
{
	auto result = invokeCallback(amx, name, params); //call Java function if there is any to execute
	if (retval)
		*retval = result; //Set returnvalue
	if (shouldCancelCallback(name, result)) { //If the callback should be canceled (just a value checking method, returning true or false)
		sampgdk_logprintf("Canceling callback %s with returnvalue %i", name, *retval);
		return false;
	} 
	else //If the callback should not be canceled
	{
		auto hook = callHookedCallback(amx, name, params); //Execute custom hook
		if (hook)
		{
			auto willCancel = hook[1];
			if (retval)
				*retval = hook[0]; //Set return value
			delete hook;
			if (willCancel == 1)
				return false; //Return false if it should cancel
		}
		return true; //If no hook was found, return true and allow normal execution
	}
}
```

**Comment by ikkentim** [comment]
@123marvin123 Tested it and you are right, returning false has no effect.

``` c++
    if (!strcmp(name, "OnRconCommand")) {
        logprintf("[plugin] OnRconCommand");
        return false;
    }
```

``` pawn
#include <a_samp>
main() return;
public OnRconCommand(cmd[])
{
	print("[gamemode] OnRconCommand");
	return 0;
}
```

**Comment by WopsS** [comment]
Strange, for me it works
```cpp
PLUGIN_EXPORT bool PLUGIN_CALL OnGameModeInit()
{
	sampgdk::logprintf("OnGameModeInit");
}

PLUGIN_EXPORT bool PLUGIN_CALL OnPlayerConnect(int PlayerID)
{
	sampgdk::logprintf("OnPlayerConnect");
}

PLUGIN_EXPORT bool PLUGIN_CALL OnPublicCall(AMX *amx, const char *name, cell *params, cell *retval) 
{
	auto Name = std::string(name);

	if (Name.compare("OnGameModeInit") == 0 || Name.compare("OnPlayerConnect") == 0)
	{
		return false;
	}

	return true;
}
```

**Comment by 123marvin123** [comment]
I think this problem only occurs when using sampgdk in combination with a pawn game mode or filter script.

**Comment by WopsS** [comment]
Let me try.

**Comment by WopsS** [comment]
Yes, you're right. You can't use sampgdk in combination with a gamemode or filterscript.

**Comment by ikkentim** [comment]
See PR

**Comment by 123marvin123** [comment]
Nice, your solution seems to fix it. Thank you.
