### ISSUE TITLE
I try to create streamer and mysql api

### ISSUE THREAD

**Issue by eXeGOODER** [Zeex/sampgdk#158]
```c++
#include "sampgdk.h"

cell Invoke(const char *name, const char *format, ...) {
	va_list args;
	va_start(args, format);
	AMX_NATIVE native = sampgdk_FindNative(name);
	cell result = sampgdk_InvokeNative(native, format, args);
	va_end(args);
	return result;
}

cell CreateDynamicObject(int modelid, float x, float y, float z, float rx, float ry, float rz, int worldid = -1, int interiorid = -1, int playerid = -1, float streamdistance = 300.0, float drawdistance = 0.0)
{
	cell result = Invoke("CreateDynamicObject", "iffffffiiiff", modelid, x, y, z, rx, ry, rz, worldid, interiorid, playerid, streamdistance, drawdistance);
	sampgdk_logprintf("Created dynamic object : %d", result);
	return result;
}
```
Using:
```pawn
CreateDynamicObject(18769, 1500.0, -1500.0, 500.0, 0.0, 0.0, 0.0);
CreateDynamicObject(18769, -1500.0, -1500.0, 500.0, 0.0, 0.0, 0.0);
CreateDynamicObject(18769, 1500.0, 1500.0, 500.0, 0.0, 0.0, 0.0);
CreateDynamicObject(18769, -1500.0, 1500.0, 500.0, 0.0, 0.0, 0.0);
```
Console:
> Created dynamic object : 1
Created dynamic object : 2
Created dynamic object : 3
Created dynamic object : 4

<hr/>
Objects aren't found
Perhaps, I made somewhere a mistake
I apologize, I am a beginner

**Comment by WopsS** [comment]
You don't need to create a custom function for **Invoke**. You can do this
```cpp
cell CreateDynamicObject(int modelid, float x, float y, float z, float rx, float ry, float rz, int worldid = -1, int interiorid = -1, int playerid = -1, float streamdistance = 300.0, float drawdistance = 0.0)
{
	static AMX_NATIVE Native = sampgdk::FindNative("CreateDynamicObject");
	return sampgdk::InvokeNative(Native, "iffffffiiiff", modelid, x, y, z, rx, ry, rz, worldid, interiorid, playerid, streamdistance, drawdistance);
}
```

**Comment by eXeGOODER** [comment]
Thank you very much!!!
I still will answer in this subject as didn't finish integration of all functions and events

**Comment by eXeGOODER** [comment]
```pawn
native orm_addvar_int(ORM:id, &var, varname[]);
```
```c++
void orm_addvar_int(int ormid, int &var, const char *varname)
{
	static AMX_NATIVE native = sampgdk::FindNative("orm_addvar_int");
	sampgdk::InvokeNative(native, "iis", ormid, &var, varname);
}
```
> COrm::AddVariable	ERROR	invalid variable name or address

**Comment by Zeex** [comment]
You can't directly pass C/C++ pointers to Pawn functions as references, they just make no sense to the AMX - it uses indexes into its internal stack/heap memory block as "addresses", and you have to convert between the two "address spaces" (i.e. native and AMX). See [Implementor’s Guide](https://github.com/Zeex/pawn/blob/master/doc/pawn-imp.pdf) for details (search for `amx_GetAddr`).

Besides, I'd recommend against using the MySQL plugin which was made for Pawn but rather some native C++ API for MySQL. If you're into ORM, I'm sure there are libraries for that too.

**Comment by eXeGOODER** [comment]
I'm sorry
mysql includes and sampgdk includes conflicts
Error and more errors:
`some copies of overloaded function "sampgdk_ *" contain configuration of "C"`

I downloaded MySQL includes from `http://dev.mysql.com/downloads/connector/c/` and put it to `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include` and `#include <mysql.h>`
