### ISSUE TITLE
build sampgdk

### ISSUE THREAD

**Issue by KennyDalglish** [Zeex/sampgdk#159]
Hi. I am build SAMPGDK:
`CMake Error at /usr/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find SAMPSDK (missing: SAMPSDK_DIR SAMPSDK_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSAMPSDK.cmake:21 (find_package_handle_standard_args)
  CMakeLists.txt:30 (find_package)
`
What is the problem?

**Comment by ikkentim** [comment]
You need to specify where samp sdk is installed. Did you read the build instructions? https://github.com/Zeex/sampgdk#build-instructions
