### ISSUE TITLE
Settimer don't found

### ISSUE THREAD

**Issue by Skritwo** [Zeex/sampgdk#162]
I tried different ways to operate the timer does not work me, even I used the HelloWorld and did not work.

[http://pastebin.com/jYQjgCQk](http://pastebin.com/jYQjgCQk)

Sorry my bad english.

**Comment by ikkentim** [comment]
You can't pass in an callback which is an instance method of a class. It must either be a C style method or a static class method.

**Comment by Skritwo** [comment]
I am using a method C Style, I am passing the parameter "playerid" not an instance of class. The instance of the class is called within the function, the problem is that it is never called the function, does not print any message on console.

**Comment by maddinat0r** [comment]
Are you calling [`sampgdk::ProcessTick();`](http://zeex.github.io/sampgdk/doc/html/group__core.html#ga490d3115e9bfb6572394964a33448114) in your `ProcessTick` function?

**Comment by Skritwo** [comment]
Thanks you, now it works.
