### ISSUE TITLE
Need your help

### ISSUE THREAD

**Issue by Tracer1** [Zeex/sampgdk#163]
Good day! I use Gamemode SDK for C/C++ (GDK), and for some reason I need to connect the interception of kolbikov streamer from incognito: 

forward OnDynamicObjectMoved(STREAMER_TAG_OBJECT objectid); forward OnPlayerEditDynamicObject(playerid, STREAMER_TAG_OBJECT objectid, response, Float:x, Float:y, Float:z, Float:rx, Float:ry, Float:rz); forward OnPlayerSelectDynamicObject(playerid, STREAMER_TAG_OBJECT objectid, modelid, Float:x, Float:y, Float:z); forward OnPlayerShootDynamicObject(playerid, weaponid, STREAMER_TAG_OBJECT objectid, Float:x, Float:y, Float:z); forward OnPlayerPickUpDynamicPickup(playerid, pickupid STREAMER_TAG_PICKUP); forward OnPlayerEnterDynamicCP(playerid, checkpointid STREAMER_TAG_CP); forward OnPlayerLeaveDynamicCP(playerid, checkpointid STREAMER_TAG_CP); forward OnPlayerEnterDynamicRaceCP(playerid, checkpointid STREAMER_TAG_RACE_CP); forward OnPlayerLeaveDynamicRaceCP(playerid, checkpointid STREAMER_TAG_RACE_CP); forward OnPlayerEnterDynamicArea(playerid, areaid STREAMER_TAG_AREA); forward OnPlayerLeaveDynamicArea(playerid, areaid STREAMER_TAG_AREA); forward Streamer_OnPluginError(error[]);

Can you give an example on one of Kabakov? I have something hands do not reach. That is, will work 2 plugins, streamer and mod(based on sdk). Other functions of the stream I implemented and they work. 
Sorry for my English, I from Russia.

**Comment by WopsS** [comment]
Hello,

If I understand what you want please take a look [here](https://github.com/Zeex/sampgdk/issues/155).

**Comment by Tracer1** [comment]
Как я понял, ты русскоязычный. Можно твой ВК, на случай вопросов?
Что касаемо твоего варианта по ссылке, он надёжный?

**Comment by WopsS** [comment]
No, I don't speak Russian. That link is from this repository, someone asked something like that before, so you can trust it.

https://github.com/Zeex/sampgdk/issues/155 this is the full link if you don't trust the **<a>** tag.

**Comment by Tracer1** [comment]
Thank you very much! 
Rescued.

**Comment by WopsS** [comment]
No problem.

I will leave the response from #155 here too.

> Hello,
> I tried this way few days ago (but for ***OnPlayerEditDynamicObject***), the only way that I managed to hook it is with ***OnPublicCall*** like that:
> ```cpp
> void OnPlayerPickUpDynamicPickup(int PlayerID, int PickUpID)
> {
>         // ...
> }
> 
> PLUGIN_EXPORT bool PLUGIN_CALL OnPublicCall(AMX *amx, const char *name, cell *params, cell *retval) 
> {
> 	auto Name = std::string(name);
>         
> 	if (Name.compare("OnPlayerPickUpDynamicPickup") == 0) // Or without string with strcmp.
> 	{
> 		OnPlayerPickUpDynamicPickup(params[1], params[2]);
> 	}
> 
> 	return true;
> }
> ```

**Comment by Tracer1** [comment]
Another question to add functions such as CreateDynamicObject, you need the CreateObject template ? Or are there other options?

**Comment by Tracer1** [comment]
OnPublicCall is invoked when you call kolbikov such as onplayerupdate?

**Comment by WopsS** [comment]
For **CreateDynamicObject** take a look at this issue #158 the first reply. Sorry but I don't know what **kolbikov** is.

**Comment by Tracer1** [comment]
An example of colback 
https://wiki.sa-mp.com/wiki/OnPlayerUpdate


Not kolbikov, and colback*

**Comment by WopsS** [comment]
It should be, but I don't know really, you print every function name in **OnPublicCall** and see if it is called.

As I read somewhere **OnPublicCall** is called for all public functions which are invoked, but I didn't tested it with all of them.

**Comment by Tracer1** [comment]
Conducted tests, the solution is VERY slow because OnPublicCall called whenever the interception of colback. Imagine a server with 1000 players per second per player on the average will be about 40-50 calls colback. 1000*45 = 45 000 times call OnPublicCall later in OnPublicCall need to compare we need colback(in my case, all colback streamer: OnDynamicObjectMoved, OnPlayerPickUpDynamicPickup, etc.), for example there will be 10 pieces, in total we have 450 000 string of checks per second. It is very slow. Isn't it?

**Comment by Tracer1** [comment]
Are there alternatives OnPublicCall ? For example, the alternative that will be invoked in that case, if we intercepted colback from the plugin.

**Comment by Tracer1** [comment]
Guys, I still do not know what algorithm sampgdk tracking we need colback, I hope there's not an alternative OnPublicCall ?

**Comment by WopsS** [comment]
I don't know how slow it will be but you can call it manually and compare the results. 

But @Zeex said 

> At the moment OnPublicCall is the recommended way of hooking callbacks.
> 
> Adding callbacks to the IDL file(s) is possible too but may not work very well with future updates as the order of the callback declarations there is important and it's easy to mess them up when adding new ones with new versions of SA-MP.

**Comment by Tracer1** [comment]
I thought over the option above to use OnPublicCall not the best idea, and came up with this algorithm: 

in the gamemode.pwn: 
forward OnDynamicObjectMoved(objectid);//the function the plugin streamer 
native OnDynamicObjectMoved_(objectid);//a function to our plugin 
public OnDynamicObjectMoved(objectid){OnDynamicObjectMoved_(objectid);return true;}//when using a streamer, we call our function 

I think the point is clear. Theoretically, this option is much more economical, right?

**Comment by Tracer1** [comment]
How to make this function? 
native GetDynamicObjectPos(STREAMER_TAG_OBJECT objectid, &Float:x, &Float:y, &Float:z); 

I have here what happened:
bool GetDynamicObjectPos(int modelid, float * x, float * y, float * z)
{
	static AMX_NATIVE Native = sampgdk::FindNative("GetDynamicObjectPos");
	return static_cast<bool>(sampgdk::InvokeNative(Native, "ifff", modelid, &x, &y, &z));
}

Not tested, but theoretically, right?

**Comment by IstuntmanI** [comment]
I know that most probably my response is way too late, but maybe others will look here in the future:
1. A ```static_cast``` call looks like ```static_cast< DATA_TYPE >( PARAMETER )```. Example: ```static_cast< unsigned int >( 5.0 )``` .
2. You need to use "R" instead of "f" because you are passing a cell pointer of which address will be modified in that native. From ```sampgdk.h``` (above InvokeNative):
```C++
/**
 * \brief Invokes a native function with the specified argument
 *
 * Argument types are specified via \p format where each character, or
 * *specifier*, corresponds to a single argument. The following format
 * specifiers are supported:
 *
 * Specifier | C/C++ type    | Description
 * :-------- | :------------ | :-------------------------------------
 * i         | int           | integer value
 * d         | int           | integer value (same as 'i')
 * b         | bool          | boolean value
 * f         | double        | floating-point value
 * r         | const cell *  | const reference (input only)
 * R         | cell *        | non-const reference (both input and output)
 * s         | const char *  | const string (input only)
 * S         | char *        | non-const string (both input and output)
 * a         | const cell *  | const array (input only)
 * A         | cell *        | non-const array (both input and output)
 *
 * \remarks For the 'S', 'a' and 'A' specifiers you have to specify the size
 * of the string/array in square brackets, e.g. "a[100]" (fixed size)
 * or s[*2] (size passed via 2nd argument).
 *
 * \note In Pawn, variadic functions always take their variable arguments
 * (those represented by "...") by reference. This means that for such
 * functions you have to use the 'r' specifier where you would normally
 * use 'b', 'i' 'd' or 'f'.
 *
 * \param native pointer to the native function.
 * \param format argument types
 * \param ... arguments themselves
 *
 * \returns function's return value
 *
 * \see sampgdk_GetNatives()
 * \see sampgdk_FindNative()
 * \see sampgdk_InvokeNativeV()
 * \see sampgdk_InvokeNativeArray()
 */
```

So it becomes
```C++
bool GetDynamicObjectPos( int objectid, float * x, float * y, float * z )
{
	static AMX_NATIVE Native = sampgdk::FindNative( "GetDynamicObjectPos" );
	return !!sampgdk::InvokeNative( Native, "iRRR", objectid, x, y, z );
}
```
(I use ```!!``` to convert it to a ```bool```, because InvokeNative returns an ```int```. There's no need for ```static_cast```)

------------

This issue needs to be closed.
