### ISSUE TITLE
Making this project to Visual Studio

### ISSUE THREAD

**Issue by Bigbossbro08** [Zeex/sampgdk#165]
Your Gamemode SDK for C/C++ (GDK) is quite satisfying project. I really appreciate that but I found many difficulty while building this project.

Building this project is very hard process and annoying. Will you please release a project for Visual Studio?

**Comment by ziggi** [comment]
Just read this: https://github.com/Zeex/sampgdk/wiki/Setting-up-GDK-with-CMake

**Comment by Bigbossbro08** [comment]
Thanks it helps a lot. BTW, can I make DK22PAC's SDK plugin and add new ped with AI decision make it work with SAMP server?

**Comment by ziggi** [comment]
> BTW, can I make DK22PAC's SDK plugin and add new ped with AI decision make it work with SAMP server?

I think it's possible. But it will work only on clients with the same plugin.
