### ISSUE TITLE
OnRconCommand() doesn't work

### ISSUE THREAD

**Issue by buridan1999** [Zeex/sampgdk#170]
Hello, guys. Please excuse me for my bad English.
I wrote little code in  OnRconCommand()  , but it doesn't work. When I enter /stics command in console of the server, nothink happen. If I have a mistake in code, please tell me, but I cheked it.

PLUGIN_EXPORT bool PLUGIN_CALL OnRconCommand(const char *cmd) {
	if (strcmp(cmd, "/stisc") == 0) {
		showticks = true;
		sampgdk::logprintf("Tick count set else");
		SendClientMessage(0, 0x00FF00FF, "TICKS");
		return true;
	}
	return false;
}

**Comment by Zeex** [comment]
Hi, 

Please see this issue: https://github.com/Zeex/sampgdk/issues/139.

In short: it works only if you have a filterscript with (empty) OnRconCommand.
