### ISSUE TITLE
Problem with 3DText [ UPDATED ]

### ISSUE THREAD

**Issue by buridan1999** [Zeex/sampgdk#173]
I try to use 2 function:
Create3DTextLabel()
CreatePlayer3DTextLabel()

but no one is work, I don't see text, also I can't test will see this text others players.

`

PLUGIN_EXPORT bool PLUGIN_CALL OnPlayerSpawn(int playerid) {
	SetPlayerVirtualWorld(playerid, VIRTUAL_WORLD_STANDART);
	char first_last_name[MAX_FIRSTNAME + MAX_LASTNAME + 1];
	PlayerClass* pointer_p = _mapsOfPlayers.GetPlayerPointer(playerid);
	sprintf(first_last_name, "%s %s", pointer_p->bGetCharFirstname(), pointer_p->bGetCharLastname());
	int text_id = Create3DTextLabel(first_last_name, 0xFFFFFFFF, 0.0, 0.0, 0.0, 50.0, VIRTUAL_WORLD_STANDART, 1);
	Attach3DTextLabelToPlayer(
		text_id,
		playerid, 0.0, 0.0, CHAR_NAMES_HEIGHT);

	CreatePlayer3DTextLabel(playerid, first_last_name, 0xFFFFFFFF, 0.0, 0.0, 0.0, 20, playerid, INVALID_VEHICLE_ID, 0);
	return true;
}

`

**Comment by WopsS** [comment]
This is not a problem with the plugin, you can't see 3D labels attached to you (as far as I remember).

**Comment by buridan1999** [comment]
okey, thanks for answer.

**Comment by WopsS** [comment]
No problem.

**Comment by buridan1999** [comment]
Excuse me again. But I tested 3Dtext functions, and it doesn't work even if I create 3Dtext for all players by this function > Create3DTextLabel(), what reasons may be?

**Comment by ikkentim** [comment]
@buridan1999 it should works just fine. if you could share the code where you create the textdraw...

**Comment by buridan1999** [comment]
This code:
`PLUGIN_EXPORT bool PLUGIN_CALL OnPlayerSpawn(int playerid) {
	SetPlayerVirtualWorld(playerid, VIRTUAL_WORLD_STANDART);
	char first_last_name[MAX_FIRSTNAME + MAX_LASTNAME + 1];
	PlayerClass* pointer_p = _mapsOfPlayers.GetPlayerPointer(playerid);
	sprintf(first_last_name, "%s %s", pointer_p->bGetCharFirstname(), pointer_p->bGetCharLastname());
//	float x, y, z;
//	GetPlayerPos(playerid, &x, &y, &z);
	int text_id = Create3DTextLabel(first_last_name, 0x008080FF, 0.0, 0.0, 0.0, 50.0, VIRTUAL_WORLD_STANDART, 1);
	Attach3DTextLabelToPlayer(
		text_id,
		playerid, 0.0, 0.0, CHAR_NAMES_HEIGHT
	);

	CreatePlayer3DTextLabel(playerid, first_last_name, 0x008080FF, 0.0, 0.0, 0.0, 20, playerid, INVALID_VEHICLE_ID, 0);

	Create3DTextLabel("ТЕСТ!", 0x008080FF, 1958.33, 1343.12, 15.36, 50.0, VIRTUAL_WORLD_STANDART, 1);
	return true;
}`

char first_last_name[] doesn't empty, I tested it.

**Comment by ikkentim** [comment]
Once again, like WopsS said, you can't see a 3DTextLabel if it is attached to yourself, no matter to which players the 3DTextLabel is set to be visible. The is simply how SA-MP works.

**Comment by buridan1999** [comment]
But I don't see this 3Dtext too!

Create3DTextLabel("ТЕСТ!", 0x008080FF, 1958.33, 1343.12, 15.36, 50.0, VIRTUAL_WORLD_STANDART, 1);

**Comment by ikkentim** [comment]
What value is VIRTUAL_WORLD_STANDART ? It must be 0 or higher.

**Comment by buridan1999** [comment]
It is - "0"
`#define VIRTUAL_WORLD_STANDART (0)`

**Comment by ikkentim** [comment]
Then I can't quickly spot the error, sorry! You could try the same code in pawn, I'm certain it will not work there either. You can then ask for further assistance on the sa-mp forums

**Comment by buridan1999** [comment]
Okey, thanks fot try to help me))

**Comment by buridan1999** [comment]
If I create 3Dtext in Pawno - gamemode it work... But I need to use this function from my c++ code =(

**Comment by ikkentim** [comment]
I'm just guessing here... You can try replacing your doubles with floats:

```
Create3DTextLabel("ТЕСТ!", 0x008080FF, 1958.33f, 1343.12f, 15.36f, 50.0f, VIRTUAL_WORLD_STANDART, 1);
```

**Comment by buridan1999** [comment]
Unfortunately it doesn't help

**Comment by buridan1999** [comment]
Yes! I sure for position, because in pawn code i see 3Dtext.

**Comment by Vinigas** [comment]
Firstly, your C-string is too short (array of chars). C-strings always need to have NULL symbol at it's end ( \0 ). In your example you create MAX_FIRSTNAME+MAX_LASTNAME+1 size C-string which in simple words should be MAX_FIRSTNAME+MAX_LASTNAME+2. Plus I'm not sure if sprintf function adds '\0' symbol at the end of C-string.

I am not in sampgdk gamemode development anymore, but I suggest you to try "ТЕСТ!\0", maybe it is the problem?

Also you can use C++ strings which is comfortable. But you will need to convert it to C string everytime you want to pass it to sampgdk library methods.

**Comment by ikkentim** [comment]
> "ТЕСТ!\0",

C/++ automatically terminates strings.

**Comment by buridan1999** [comment]
It's adding automatically. But I try it for test, and it doesn't help.

**Comment by buridan1999** [comment]
Hey, guys. Anyone find solution of this problem?

**Comment by WopsS** [comment]
Hello,

Add
```cpp
float X, Y, Z;
sampgdk::GetPlayerPos(Id, &X, &Y, &Z);
sampgdk::Create3DTextLabel("Test", 0x008080FF, X, Y, Z, 40.0, 0);
```
at **OnPlayerCommandText** and execute a random command, does it work?

**Comment by buridan1999** [comment]
E0135	namespace "sampgdk" не содержит члена (does not contain member) "sampgdk_Create3DTextLabel"	helloworld	g:\sampServer\cppServer\server\PROJECT_SOURCE_DIR\helloworld.cpp	123

**Comment by WopsS** [comment]
Delete **sampgdk::** if you don't use **SAMPGDK_CPP_WRAPPERS**.

**Comment by buridan1999** [comment]
I use them. And after I delete sampgdk:: it compiled, but I don't see 3Dtext, I think maybe it's problem with function, because in Pawn it's work.

**Comment by WopsS** [comment]
It works for me, so it isn't a problem with the plugin or the function. Show us the full implementation.

**Comment by buridan1999** [comment]
So -->

`PLUGIN_EXPORT bool PLUGIN_CALL OnPlayerConnect(int playerid) {
	//SetPlayerVirtualWorld(playerid, VIRTUAL_WORLD_STANDART);
	++numberOfActivePlayers;
	bCheck_bAutorization_state();
	bCheck_bPlayerClass_state();

	// Создаём новый объект - класс Игрок
	char player_nickname[MAX_PLAYER_NAME + 1];
	char* pointer_to_str = &player_nickname[0];
	GetPlayerName(playerid, player_nickname, MAX_PLAYER_NAME + 1);
	PlayerClass* p_player_class = new PlayerClass(playerid, player_nickname);
	_mapsOfPlayers.AddPlayerToMap(playerid, p_player_class);
	delete pointer_to_str;
	pointer_to_str = 0;
	// ------------------------------------------------------------------------------
	Autorization(playerid);
	
	SendClientMessage(playerid, -1, "Сейчас должны выскочить диалоги ввода фамилии, имени.");
	// ЗАГРУЗКА ДАННЫХ ПЕРСА
	ShowPlayerDialog(playerid, DIALOG_ENTER_FIRSTNAME, DIALOG_STYLE_INPUT, "Фамилия", "Придумайте фамилию своему персонажу:", "ОК", "ОТМЕНА");
	SetSpawnInfo(playerid, 0, 0, 1958.33, 1343.12, 15.36, 269.15, 26, 36, 28, 150, 0, 0);
	SpawnPlayer(playerid);

	return true;
}`


`PLUGIN_EXPORT bool PLUGIN_CALL OnPlayerSpawn(int playerid) {
	SetPlayerVirtualWorld(playerid, VIRTUAL_WORLD_STANDART);
	char first_last_name[MAX_FIRSTNAME + MAX_LASTNAME + 2];
	PlayerClass* pointer_p = _mapsOfPlayers.GetPlayerPointer(playerid);
	sprintf(first_last_name, "%s %s", pointer_p->bGetCharFirstname(), pointer_p->bGetCharLastname());
//	float x, y, z;
//	GetPlayerPos(playerid, &x, &y, &z);
//	int text_id = Create3DTextLabel(first_last_name, 0x008080FF, 0.0, 0.0, 0.0, 50.0, VIRTUAL_WORLD_STANDART, 1);
//	Attach3DTextLabelToPlayer(
//		text_id,
//		playerid, 0.0, 0.0, CHAR_NAMES_HEIGHT
	float X, Y, Z;
	GetPlayerPos(playerid, &X, &Y, &Z);
	Create3DTextLabel("Test", 0x008080FF, X, Y, Z, 40.0, VIRTUAL_WORLD_STANDART, 0);

	CreatePlayer3DTextLabel(playerid, first_last_name, 0x008080FF, 0.0, 0.0, 0.0, 20, playerid, INVALID_VEHICLE_ID, 0);

	Create3DTextLabel("ТЕСТ!", 0x008080FF, 1958.33f, 1343.12f, 15.36f, 50.0f, VIRTUAL_WORLD_STANDART, 1);
	return false;
}`

**Comment by WopsS** [comment]
> Add
> ```cpp
> float X, Y, Z;
> sampgdk::GetPlayerPos(Id, &X, &Y, &Z);
> sampgdk::Create3DTextLabel("Test", 0x008080FF, X, Y, Z, 40.0, 0);
> ```
> at **OnPlayerCommandText** and execute a random command, does it work?

**Comment by buridan1999** [comment]
What a ###. When i print command in chat, it work.
BUT WHY IT DOESN'T WORK IN THIS OnPlayerSpawn PUBLIC ??!!

**Comment by WopsS** [comment]
I don't know, do a debug for **X, Y, Z**.

**Comment by buridan1999** [comment]
Maybe when I call function Spawn() he do this function and coordinates change, maybe if i set timer for maybe 1 second it will be work....

**Comment by ikkentim** [comment]
I'd like to bet, that your player's virtual world isn't equal to `VIRTUAL_WORLD_STANDART`.

**Comment by buridan1999** [comment]
equal

**Comment by buridan1999** [comment]
Okey, I find solution of a problem. It must be a little pause after spawn() call. 
Thanks to all who was tried to hrlp me!
