### ISSUE TITLE
Plugin crashing server

### ISSUE THREAD

**Issue by NegativeIQ** [Zeex/sampgdk#174]
static cell AMX_NATIVE_CALL TestNativeFunc(AMX *amx, cell *params)
	{
		sampgdk_logprintf("Shit is working....");
		return 1;
	}

	AMX_NATIVE_INFO PluginNatives[] = {
		//{ "DefineNewItem", DefineNewItem },
		//{ "GetItemName", GetItemName },
		{ "TestNativeFunc", TestNativeFunc },
		{ 0, 0 }
	};

	PLUGIN_EXPORT int PLUGIN_CALL AmxLoad(AMX *pAMX)
	{
		return amx_Register(pAMX, PluginNatives, -1);
	}

	PLUGIN_EXPORT int PLUGIN_CALL AmxUnload(AMX *amx)
	{
		return AMX_ERR_NONE;
	}

	PLUGIN_EXPORT unsigned int PLUGIN_CALL Supports() {
		return sampgdk::Supports() | SUPPORTS_PROCESS_TICK | SUPPORTS_AMX_NATIVES;
	}

I created plugin (mostly) using wiki tutorial, only changed directories layout and path for include files in source...Also added AmxLoad AmxUnload into .def. Plugin compiles without errors, and i dont even call any natives i exported (and it still just crashes after load - please note it says loaded and server count's it as loaded).

If i remove SUPPORTS_AMX_NATIVES it works fine, but i cant use export my new functions into pawn...

[EDIT]By the way, i tested this without any other plugins on a clean GM

**Comment by WopsS** [comment]
Add in your main file
```cpp
extern void* pAMXFunctions;
```
and at **Load** add
```cpp
pAMXFunctions = Data[PLUGIN_DATA_AMX_EXPORTS];
```

You get that crash because you need AMX exports in your plugin, if you don't have them you have an
> Access violation reading location

**Comment by NegativeIQ** [comment]
Thank you very much! That fixed it.

Why is these not handled by GDK itself since we do pass ppData?

**Comment by WopsS** [comment]
No problem.

> Why is these not handled by GDK itself since we do pass ppData?

I don't know, @Zeex could tell us why.
