### ISSUE TITLE
Keys state

### ISSUE THREAD

**Issue by buridan1999** [Zeex/sampgdk#179]
I try to do some action when player holding key, and use information about how can I do it from this samp_wiki page -> http://wiki.sa-mp.com/wiki/OnPlayerKeyStateChange#Introduction

And when I paste this fragment of code:
`// HOLDING(keys)
#define HOLDING(%0) \
	((newkeys & (%0)) == (%0))`
compiler said me, that it need identificator. Where is my mistake?

**Comment by IstuntmanI** [comment]
In C++ you can name your macro's parameters like how you want. They aren't using a percent sign.
```C++
#define HOLDING(keys) ((newkeys & (keys)) == (keys))
```

By the way, please don't post this kind of problems on GitHub issues. GitHub issues should be only for project's faults and eventually suggestions. For these kind of problems you have the forum or you can search on Google (stackoverflow *wink* *wink*).
