### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by Y-Less** [Zeex/sampgdk#183]
> For example, OnPlayerConnect has a badret of false. This means that when you return false in OnPlayerConnect inside your plugin it will not be called in subsequent plugins, i.e. plugins that have been loaded before yours, as well as the gamemode.

"subsequent" means "after", but the wiki says "before" - which is it please?  Thanks.  I read that as meaning that callbacks in plugins are called in reverse order - last loaded to first loaded, is that true?

Edit;

Obviously I'm talking about this page:

https://github.com/Zeex/sampgdk/wiki/Callback-return-values

**Comment by ikkentim** [comment]
AFAIK The plugins loaded before. The "first" plugin is the plugin where the callback is first processed, because the hooks are applies from first to last plugin, making the last plugin the first where the callback is called on.

**Comment by Zeex** [comment]
@ikkentim is correct, callbacks are called in reverse order - from last loaded plugin to first. Sorry, I didn't realize it was confusing. I'll edit the wiki to reflect this.
