### ISSUE TITLE
Have not NPC callbacks

### ISSUE THREAD

**Issue by MeFFoS** [Zeex/sampgdk#198]
Have not NPC callbacks:
NPC:OnClientMessage
NPC:OnPlayerDeath
NPC:OnPlayerStreamIn
NPC:OnPlayerStreamOut
NPC:OnPlayerText
NPC:OnRecordingPlaybackEnd
NPC:OnVehicleStreamIn
NPC:OnVehicleStreamOut 
http://wiki.sa-mp.com/wiki/Category:Scripting_Callbacks

**Comment by IstuntmanI** [comment]
As far as I know, those callbacks are called only in scripts placed in `npcmodes`. sampGDK catches only callbacks that are called in the gamemode, not sure. But yeah, this should be addressed somehow, maybe an overload for every callback to also include the AMX pointer as an argument before the rest of callback's arguments, if possible. Maybe this plugin should also register some AMX native to help us to identify each script's pointer if overloads like those would be made.
