### ISSUE TITLE
Loading filterscripts gets progressivly slower

### ISSUE THREAD

**Issue by arfni** [Zeex/sampgdk#200]
Hello,

I've opened this issue in Incognito's streamer repository and was told that it's caused by the sampgdk.

>My server relies on filterscripts being constantly loaded and unloaded, I've noticed it gets progressively slower over time and done some testing.
>
>Loading filterscripts with the streamer:
>https://pastebin.com/sPgybsE2
>
>Loading filterscripts without the streamer:
>https://pastebin.com/kUsdiTEL

Here's what Incognito wrote:

>I was curious about this and tested some of the earlier versions. Interestingly, 2.7.0 was unaffected. The problem seemed to crop up in 2.7.1. The only major change in that version was an sampgdk update, so I built the sampgdk helloworld plugin and tested it just now. The filterscripts began to load progressively slower again once that plugin was loaded.
>
>Edit: I should say that I haven't reviewed sampgdk's code in a long time, so I'm not exactly sure why this is happening. It looks like a memory leak of some kind to me, though. You might have more success asking on the sampgdk repo.

**Comment by Zeex** [comment]
Can you show the code that you used to measure FS loading times?

**Comment by arfni** [comment]
```new lTick;

for( new i = 0; i < 500; i ++ )
{
    lTick = GetTickCount( );
    SendRconCommand( "loadfs FSNAME" );
    printf( "Loaded in %dms", GetTickCount( ) - lTick );
    SendRconCommand( "unloadfs FSNAME" );
}```

**Comment by Zeex** [comment]
Thanks, I will check why it gets slower. Probably something is not cleaned up properly during unload.
