### ISSUE TITLE
Minimum required version should be 3.1

### ISSUE THREAD

**Issue by Y-Less** [Zeex/sampgdk#202]
CMakeLists.txt states a minimum version of 2.8.12:

https://github.com/Zeex/sampgdk/blob/60934cab2bf3c68fd86052fdae6bd9bbd432e46d/CMakeLists.txt#L3

But the script calls `cmake -E env`:

https://github.com/Zeex/sampgdk/blob/60934cab2bf3c68fd86052fdae6bd9bbd432e46d/CMakeLists.txt#L102

Which wasn't introduced until 3.1.

**Comment by Zeex** [comment]
Fixed
