### ISSUE TITLE
Trouble with std::cout and ENDL

### ISSUE THREAD

**Issue by boreek** [Zeex/sampgdk#203]
Hello
This is not a critical issue, but it made me spend a few hours.

**Code:**
```c++
PLUGIN_EXPORT bool PLUGIN_CALL OnGameModeInit() {
  std::cout << "GAME MODE INIT";
  return true;
}
```

**Trouble:**
The message "GAME MODE INIT" will appear only when the server is turned off
But, if I add "endl" or "\n", then the message is output correctly (when this callback is called)

**I use:**
1. docker image i386:ubuntu:18.04 (for compile)
2. gdk 4.6.2 amalgamation

**What could be the problem?**

**Comment by Zeex** [comment]
That's just how stdout works, it buffers content until your print a newline or flush it. You could also use `logprintf` (or `sampgdk::logprintf`).
