### ISSUE TITLE
Typo (badref) in a_samp OnVehicleRespray

### ISSUE THREAD

**Issue by ikkentim** [Zeex/sampgdk#211]
https://github.com/Zeex/sampgdk/blob/master/lib/sampgdk/a_samp.idl#L552

I was looking for a simple list of sa:mp callbacks and thought I would borrow sampgdk's one. I noticed on line 552 it says `badref` instead of `badret`. I can't find any handling for `badref`, is this a typo?

```
[callback, badref(false)] bool OnVehicleRespray(int playerid, int vehicleid, int color1, int color2);
```

**Comment by Zeex** [comment]
Yep, it's a typo. Fixed it, thanks.
