### ISSUE TITLE
Rewriting arguments passed by reference

### ISSUE THREAD

**Issue by vsergeenko777** [Zeex/sampgdk#222]
sampgdk has a issue with passing arguments by reference in code-generated natives. If called native doesn't write values to arguments by reference, sampgdk will return undefined values from fakeamx stack/heap. Instead of keeping the original values.

Demo of issue using GetVehiclePos. Create a vehicle:
```cpp
int vehicle = CreateVehicle(400, 111.0f, 222.0f, 333.0f, 0.0f, 0, 0, 0, false);
sampgdk::logprintf("vehicle: %d", vehicle);
```

Try get the position of this vehicle, and then get the position of a non-existent vehicle:
```cpp
float pos1[3]{ 0.0f, 0.0f, 0.0f };
sampgdk::logprintf("vehicle pos: %f %f %f", pos1[0], pos1[1], pos1[2]);
GetVehiclePos(vehicle, &pos1[0], &pos1[1], &pos1[2]);
sampgdk::logprintf("vehicle pos: %f %f %f", pos1[0], pos1[1], pos1[2]);

float pos2[3]{ 0.0f, 0.0f, 0.0f };
sampgdk::logprintf("invalid vehicle pos: %f %f %f", pos2[0], pos2[1], pos2[2]);
GetVehiclePos(999, &pos2[0], &pos2[1], &pos2[2]); // Non-existent vehicle with id 999
sampgdk::logprintf("invalid vehicle pos: %f %f %f", pos2[0], pos2[1], pos2[2]);
```

Result:
```
vehicle: 1
vehicle pos: 0.000000 0.000000 0.000000
vehicle pos: 111.000000 222.000000 333.000000
invalid vehicle pos: 0.000000 0.000000 0.000000
invalid vehicle pos: 111.000000 222.000000 333.000000 <--- Invalid values. Must be zeros.
```

Try to do same, but through InvokeNative:
```cpp
AMX_NATIVE native = sampgdk::FindNative("GetVehiclePos");

float pos1[3]{ 0.0f, 0.0f, 0.0f };
sampgdk::logprintf("vehicle pos: %f %f %f", pos1[0], pos1[1], pos1[2]);
sampgdk::InvokeNative(native, "iRRR", vehicle, &pos1[0], &pos1[1], &pos1[2]);
sampgdk::logprintf("vehicle pos: %f %f %f", pos1[0], pos1[1], pos1[2]);

float pos2[3]{ 0.0f, 0.0f, 0.0f };
sampgdk::logprintf("invalid vehicle pos: %f %f %f", pos2[0], pos2[1], pos2[2]);
sampgdk::InvokeNative(native, "iRRR", 999, &pos2[0], &pos2[1], &pos2[2]); // Non-existent vehicle with id 999
sampgdk::logprintf("invalid vehicle pos: %f %f %f", pos2[0], pos2[1], pos2[2]);
```

Result:
```
vehicle: 1
vehicle pos: 0.000000 0.000000 0.000000
vehicle pos: 111.000000 222.000000 333.000000
invalid vehicle pos: 0.000000 0.000000 0.000000
invalid vehicle pos: 0.000000 0.000000 0.000000 <--- Valid original values
```

A simple fix for GetVehiclePos is to change three lines:
```cpp
sampgdk_fakeamx_push(1, &x_);
sampgdk_fakeamx_push(1, &y_);
sampgdk_fakeamx_push(1, &z_);
```
```cpp
sampgdk_fakeamx_push_float(*x, &x_);
sampgdk_fakeamx_push_float(*y, &y_);
sampgdk_fakeamx_push_float(*z, &z_);
```

It is necessary to make similar changes to the generator of natives code.

I noticed this when I was trying to figure out a problem within [this](https://github.com/samp-incognito/samp-streamer-plugin/blob/ce28f825ccd13a5d4da4610200f9d4c9f3ab31d5/src/streamer.cpp#L226-L233) streamer code. In it, the IsPlayerInAnyVehicle function doesn't guarantee that subsequent calls to GetPlayerVehicleID and GetVehiclePos will succeed. When destroying an occupied vehicle, IsPlayerInAnyVehicle returns true for a short time, and GetVehiclePos fails, resulting in an invalid player position being written to player.position. This code is somewhat incorrect, but sampgdk should not overwrite values passed by reference when the called native does not.

**Comment by Zeex** [comment]
Thanks for the detailed info 👍 I'll look into this.
